## Site metadata ##

title: Piracy - Fernbacher
description: What i use to pirate

### Built settings ###

url: "https://fernbacher.github.io"
baseurl: "/piracy"

github_username: Fernbacher

theme: jekyll-theme-cayman

plugins:
  - jekyll-tabs

