remote_theme: sharadcodes/jekyll-theme-retro-yellow
title: Piracy Fernbacher
markdown: kramdown
color_scheme: "yellow"
#Other shit
author:
  name: Fernbacher
  email: suckmycock@fuckyou.com

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
