remote_theme: sharadcodes/jekyll-theme-dark-reader
title: Piracy Fernbacher
markdown: kramdown

#Other shit
author:
  name: Fernbacher
  email: suckmycock@fuckyou.com
  
paginate: 3

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
